-- Saved trips are only visible to logged-in tourists. A visitor who is not
-- logged in still gets their generated plan recorded, but only so the admin
-- side has statistics: the row has no owner (user_id is null) and nobody can
-- open it again. That makes the guest-token ownership from the first trip
-- migration pointless -- there is no guest identity to hand a plan back to.
alter table trips drop constraint if exists trips_has_owner;
drop index if exists trips_guest_idx;
alter table trips drop column if exists guest_token_hash;

-- user_id null = recorded for stats only (visitor was not logged in).
comment on column trips.user_id is 'Owner. NULL = plan generated by a visitor who was not logged in; kept for admin statistics only and never shown to anyone as a saved trip.';

-- Stats queries slice by date and by owned-vs-anonymous.
create index if not exists trips_anonymous_created_idx on trips (created_at desc) where user_id is null;
