from fastapi import APIRouter, HTTPException
from src.services.trip_planner.models import TripInput, TripResponse
from src.services.trip_planner.orchestrator import TripBuilderService
from src.services.trip_planner.llm_extractor import LLMTripPlanner

router = APIRouter(prefix="/trip", tags=["Trip Planner"])
service = TripBuilderService()


@router.post("/llm", response_model=TripResponse)
def generate_trip_llm(user_input: TripInput):
    hotel, candidates = service.build_candidate_list(user_input)
    if not candidates:
        return TripResponse(itinerary=[], total_distance_km=0, total_cost_estimate=0, note="Not found")

    pace_inst, budget_inst = service.get_dynamic_instructions(user_input)
    planner = LLMTripPlanner(candidates, start_point=hotel)

    # No fallback to a deterministic planner on failure -- surface the error
    # so the frontend shows it and lets the user retry, per the plan's
    # trip-planner failure-handling decision.
    try:
        final_itinerary = planner.solve_route_with_llm(user_input, pace_inst, budget_inst)
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Trip planning failed: {e}")

    total_dist = sum(sum(s.distance_km for s in day.schedule) for day in final_itinerary)
    total_cost = sum(day.day_cost_estimate for day in final_itinerary)
    summary_data = service.create_trip_summary(final_itinerary, total_dist, total_cost)

    return TripResponse(
        itinerary=final_itinerary,
        total_distance_km=round(total_dist, 2),
        total_cost_estimate=round(total_cost, 2),
        note=f"Generated by AI ({planner.default_model})",
        summary=summary_data,
    )
